version: '3.5'
services:
    ocrmypdf-watchdog:
        container_name: OCRmyPDF
        network_mode: none
        #image: dennischan/ocrmypdf:arm64-latest
        build: '.'
        restart: always
        environment:
            OCRMYPDF_IN: /in
            OCRMYPDF_OUT: /out
            WATCHDOG_FREQUENCY: 5
            WATCHDOG_EXTENSIONS: pdf,jpg,jpeg,tif,tiff,png,gif
            OCRMYPDF_BINARY: ocrmypdf
            OCRMYPDF_PARAMETER: -l chi_sim+eng+equ --rotate-pages --deskew --jobs 4 --output-type pdfa
        ports: 
            - "8888:8000"
        volumes:
            - /var/media/ssdDATA/ocrfolder/input:/in
            - /var/media/ssdDATA/ocrfolder/output:/out
