version: '3.5'
services:
    ocrmypdf-watchdog:
        container_name: OCRmyPDF
        network_mode: none
        #image: dennischancs/ocrmypdf
        build: '.'
        restart: always
        ports: 
            - "5250:5250"
        environment:
            OCRMYPDF_IN: /in
            OCRMYPDF_OUT: /out
            WATCHDOG_FREQUENCY: 5
            WATCHDOG_EXTENSIONS: pdf,jpg,jpeg,tif,tiff,png,gif
            OCRMYPDF_BINARY: ocrmypdf
            OCRMYPDF_PARAMETER: -l chi_sim+eng+equ --tesseract-timeout 300 --rotate-pages --deskew --jobs 4 --output-type pdfa
        volumes:
            - /var/media/ssdDATA/ocrfolder/input:/in
            - /var/media/ssdDATA/ocrfolder/output:/out
